### ISSUE TITLE
regarding google colab

### ISSUE THREAD

**Issue by vainaijr** [AntreasAntoniou/HowToTrainYourMAMLPytorch#13]
hello, is it possible to convert the code in jupyter notebook form, so that it can be run in google colab.

it would make it possible to run it without having a local GPU, and we can use google colab GPU.

thanks

**Comment by AntreasAntoniou** [comment]
Converting the running script into a jupyter notebook should be trivial. Unfortunately, I don't have any spare time at the moment to work on this. However, feel free to develop such a notebook and make a pull request to add it to this repo.

**Comment by vainaijr** [comment]
Hello,

is it possible to add visualization, to plot support set and query set images, (to tensorboard), it will make it easier to understand what images are being used in the support set and in the query set.

google colab has TPU support also, but the only example I could find, was training MNIST on xla repository, and it would be different for MAML++, can those TPUs be used to accelerate training.

**Comment by AntreasAntoniou** [comment]
As I previously said, you are welcome to implement those features and issue a PR.
