### ISSUE TITLE
Warm restarts?

### ISSUE THREAD

**Issue by aatkinson** [AntreasAntoniou/HowToTrainYourMAMLPytorch#26]
Hi Antreas, thanks for providing this code!

Per your paper and code you use a cosine-annealed learning rate in the outer loop, but it is unclear if you also use warm restarts, as described in the [SGDR](https://arxiv.org/abs/1608.03983) paper which introduced this schedule.

Have you experimented with warm restarts at all, or am I just missing something?

**Comment by brando90** [comment]
did you get an answer to this?

**Comment by aatkinson** [comment]
Answered in your issue here :) https://github.com/AntreasAntoniou/HowToTrainYourMAMLPytorch/issues/43
no warm restarts
