### ISSUE TITLE
While saving model, save optimizer state dict as well

### ISSUE THREAD

**Issue by pandeydeep9** [AntreasAntoniou/HowToTrainYourMAMLPytorch#31]
Hi there,

Thanks for the great code.

I was experimenting with checkpoints/resuming experiments from specified epoch for maml experiments and noticed that the optimizer state dict is not saved. 
 
I think since outer loop uses adam optimizer we should save the optimizer state dict along with the model state dict i.e. in few_shot_learning_system.py save_model, adding state['optimizer'] = self.optimizer.state_dict() and in load_model adding  self.optimizer.load_state_dict(state['optimizer']). 

Let me know if this does not make sense.

**Comment by AntreasAntoniou** [comment]
Makes perfect sense and yes you are right. I noticed it some time ago and
forgot to update the code. Feel free to push a PR. I'll review it.
