### ISSUE TITLE
Missing attribute self.use_bias in init of BatchNormReLUConv

### ISSUE THREAD

**Issue by simonguiroy** [AntreasAntoniou/HowToTrainYourMAMLPytorch#4]
Here there should be a line `self.use_bias = use_bias` 

https://github.com/AntreasAntoniou/HowToTrainYourMAMLPytorch/blob/09dbacc7415bb0659f84f40d5c264179d80a9bd6/meta_neural_network_architectures.py#L53

**Comment by AntreasAntoniou** [comment]
This has now been fixed. Thanks for spotting this and letting me know.
