### ISSUE TITLE
Dataset links

### ISSUE THREAD

**Issue by luizgh** [AntreasAntoniou/HowToTrainYourMAMLPytorch#6]
I have two comments about the datasets:

1. I don't see omniglot included in the github repository. There is no folder "datasets" (btw, I noticed that .gitignore is set to ignore datasets/*)
2. While the first link to download mini-imagenet is working, the second link (under "To run an experiment from the paper on Mini-Imagenet:") is broken. Also, this section refers to a .pbzip file, did you mean .tar.bz2?

Btw, thanks for making the code available. It is particularly nice that a "scripts" folder is included to make it easy to replicate the experiments.

**Comment by AntreasAntoniou** [comment]
Thanks for bringing this up to my attention. I deleted the omniglot dataset by mistake. I've now added it again. Also, I fixed the mini-imagenet links. :)

**Comment by luizgh** [comment]
Thanks, it is working now.
